schema = 3

[mod]
  [mod."github.com/aws/aws-sdk-go-v2"]
    version = "v1.26.1"
    hash = "sha256-DWXRomID11+mzn2nTzcmT5FiGn//cYGRqeXx/AX765k="
  [mod."github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream"]
    version = "v1.6.2"
    hash = "sha256-pnMCDTwCZLedttFDH9orDQVK0yxmTf6/9eQ8Y6Xh/po="
  [mod."github.com/aws/aws-sdk-go-v2/config"]
    version = "v1.27.10"
    hash = "sha256-jV7Ei6t19lRzjlhpnUpPLegglgDQ/bQaq11bEJCB2vE="
  [mod."github.com/aws/aws-sdk-go-v2/credentials"]
    version = "v1.17.10"
    hash = "sha256-dhGyBOHoJOzWF0kG6b4JPf7vioagML+LWKdJKyXsfpI="
  [mod."github.com/aws/aws-sdk-go-v2/feature/ec2/imds"]
    version = "v1.16.1"
    hash = "sha256-6ft5QSPq94r9975usoTAmi2S4C/u+tpAo/Anz+ZZYuk="
  [mod."github.com/aws/aws-sdk-go-v2/feature/s3/manager"]
    version = "v1.16.14"
    hash = "sha256-nWCtiCRLf3zPzpdn9xeSWDqCIERm5oYAZwUy2qiUSRQ="
  [mod."github.com/aws/aws-sdk-go-v2/internal/configsources"]
    version = "v1.3.5"
    hash = "sha256-yu03DOjWtb1VQSk6dNzQVw4smI9LIpE7Uj1zKvslJ2s="
  [mod."github.com/aws/aws-sdk-go-v2/internal/endpoints/v2"]
    version = "v2.6.5"
    hash = "sha256-2Nz6RzcyAuQITj1+2WoeZ0Br8RzKAlnsIs1icI0d/a0="
  [mod."github.com/aws/aws-sdk-go-v2/internal/ini"]
    version = "v1.8.0"
    hash = "sha256-v76jTAr4rEgS5en49ikLh6nuvclN+VjpOPj83ZQ3sLo="
  [mod."github.com/aws/aws-sdk-go-v2/internal/v4a"]
    version = "v1.3.5"
    hash = "sha256-w/kBk6FCD2NZSMEFonoKLyGFVP9SgLnuGPOq8gKwS1Y="
  [mod."github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding"]
    version = "v1.11.2"
    hash = "sha256-82nINVDYCeU1WL7LNHm4qGv+FDKIXPrbBRwFPmnQo9U="
  [mod."github.com/aws/aws-sdk-go-v2/service/internal/checksum"]
    version = "v1.3.7"
    hash = "sha256-s6+SBhJXRlstfZya/KhdjjkcJHndV2fLdU/KBpKmcqQ="
  [mod."github.com/aws/aws-sdk-go-v2/service/internal/presigned-url"]
    version = "v1.11.7"
    hash = "sha256-vlq9EH407bOYUQ2b8v4ljzgqmC20f8SY4nJpLBJSgZM="
  [mod."github.com/aws/aws-sdk-go-v2/service/internal/s3shared"]
    version = "v1.17.5"
    hash = "sha256-es/AWTMkXREs1tzDMU8IQfGb6GAXvgzeTdPy8/lChr8="
  [mod."github.com/aws/aws-sdk-go-v2/service/s3"]
    version = "v1.53.1"
    hash = "sha256-CY9J7kha+5hWumutV6KxGv/BHAaepV5KrN5+aylKr40="
  [mod."github.com/aws/aws-sdk-go-v2/service/sso"]
    version = "v1.20.4"
    hash = "sha256-RKShEDETh4A+CkwBrBY2E3QzhF1hePHOB6XugIXLak0="
  [mod."github.com/aws/aws-sdk-go-v2/service/ssooidc"]
    version = "v1.23.4"
    hash = "sha256-uJnOm7J+TEwR5+R8CU7KF4RvgzZARsJF18uWlc8rs3o="
  [mod."github.com/aws/aws-sdk-go-v2/service/sts"]
    version = "v1.28.6"
    hash = "sha256-jzlKFpQrNKlh2oNAQ5/np3SCrBYbnlDfLhSbbVJcMFw="
  [mod."github.com/aws/smithy-go"]
    version = "v1.20.2"
    hash = "sha256-pK6qZxyTOUE3tyujeUtHL346sSilPs6hwIbDAjswYKk="
  [mod."github.com/defval/di"]
    version = "v1.12.0"
    hash = "sha256-Fo2lfgKr+ZwjGbiIkFM28XDmz2mJIRHvV2ktG/1txSQ="
  [mod."github.com/fsnotify/fsnotify"]
    version = "v1.7.0"
    hash = "sha256-MdT2rQyQHspPJcx6n9ozkLbsktIOJutOqDuKpNAtoZY="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.3"
    hash = "sha256-svogITcP4orUIsJFjMtp+Uv1+fKJv2Q5Zwf2dMqnpOQ="
  [mod."github.com/google/flatbuffers"]
    version = "v1.12.0"
    hash = "sha256-1p4n5BxYGKbxep+5BWE4nQbhAmyVZJv5MGOkAhnBpQw="
  [mod."github.com/hashicorp/hcl"]
    version = "v1.0.0"
    hash = "sha256-xsRCmYyBfglMxeWUvTZqkaRLSW+V2FvNodEDjTGg1WA="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.1.0"
    hash = "sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE="
  [mod."github.com/jmespath/go-jmespath"]
    version = "v0.4.0"
    hash = "sha256-xpT9g2qIXmPq7eeHUXHiDqJeQoHCudh44G/KCSFbcuo="
  [mod."github.com/magiconair/properties"]
    version = "v1.8.7"
    hash = "sha256-XQ2bnc2s7/IH3WxEO4GishZurMyKwEclZy1DXg+2xXc="
  [mod."github.com/mitchellh/mapstructure"]
    version = "v1.5.0"
    hash = "sha256-ztVhGQXs67MF8UadVvG72G3ly0ypQW0IRDdOOkjYwoE="
  [mod."github.com/objectbox/objectbox-generator"]
    version = "v0.13.0"
    hash = "sha256-gfb8BAKNIxPt497SEta0JCVBXejbtLN97K0uHIpvk2I="
  [mod."github.com/objectbox/objectbox-go"]
    version = "v1.8.0"
    hash = "sha256-Q1t8IM9b5FVQd6btJKU7j/RZNNPQpSPPCI0nOiWbxYU="
  [mod."github.com/pelletier/go-toml/v2"]
    version = "v2.1.0"
    hash = "sha256-0u6oV8YMM26y2bw1oe3gLmEJc/whpNaFtEe4yOkN24c="
  [mod."github.com/sagikazarmark/locafero"]
    version = "v0.4.0"
    hash = "sha256-7I1Oatc7GAaHgAqBFO6Tv4IbzFiYeU9bJAfJhXuWaXk="
  [mod."github.com/sagikazarmark/slog-shim"]
    version = "v0.1.0"
    hash = "sha256-F92BQXXmn3mCwu3mBaGh+joTRItQDSDhsjU6SofkYdA="
  [mod."github.com/samber/lo"]
    version = "v1.39.0"
    hash = "sha256-bFJXbzFpUQM2xoNrHrlzn0RJZujd21H00zGBgo/JEb0="
  [mod."github.com/silentsokolov/go-vimeo/v2"]
    version = "v2.2.4-0.20240404053824-996199965509"
    hash = "sha256-uu4pA8dZLKDi8LA2CK3FlECBM5n5CYYzR2G9j8iLrGc="
  [mod."github.com/sourcegraph/conc"]
    version = "v0.3.0"
    hash = "sha256-mIdMs9MLAOBKf3/0quf1iI3v8uNWydy7ae5MFa+F2Ko="
  [mod."github.com/spf13/afero"]
    version = "v1.11.0"
    hash = "sha256-+rV3cDZr13N8E0rJ7iHmwsKYKH+EhV+IXBut+JbBiIE="
  [mod."github.com/spf13/cast"]
    version = "v1.6.0"
    hash = "sha256-hxioqRZfXE0AE5099wmn3YG0AZF8Wda2EB4c7zHF6zI="
  [mod."github.com/spf13/cobra"]
    version = "v1.8.0"
    hash = "sha256-oAE+fEaRfZPE541IPWE0GMeBBYgH2DMhtZNxzp7DFlY="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/spf13/viper"]
    version = "v1.18.2"
    hash = "sha256-MXYbK6w1LEaoZ2/L/STF3WU1tbK+7NwGVxUCLKPkwks="
  [mod."github.com/subosito/gotenv"]
    version = "v1.6.0"
    hash = "sha256-LspbjTniiq2xAICSXmgqP7carwlNaLqnCTQfw2pa80A="
  [mod."go.uber.org/atomic"]
    version = "v1.9.0"
    hash = "sha256-D8OtLaViqPShz1w8ijhIHmjw9xVaRu0qD2hXKj63r4Q="
  [mod."go.uber.org/multierr"]
    version = "v1.9.0"
    hash = "sha256-tlDRooh/V4HDhZohsUrxot/Y6uVInVBtRWCZbj/tPds="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20230905200255-921286631fa9"
    hash = "sha256-CyeVwjp12Wqh4ptqfi3KHCWPzOFhE8fSrP3sMjMXvec="
  [mod."golang.org/x/net"]
    version = "v0.22.0"
    hash = "sha256-pcefO4noO9I6mATKBWF6shgIjZvFg0kDsV1Jo/NsFns="
  [mod."golang.org/x/oauth2"]
    version = "v0.18.0"
    hash = "sha256-TX4CvtvHU+SGSmqlxaQqlgJjlJiOtLGYAZa0zeBfZak="
  [mod."golang.org/x/sys"]
    version = "v0.18.0"
    hash = "sha256-bIFhfFp7Sj0E1gcE3X3l/jecCfSRLgrkb8f0Yr6tVR0="
  [mod."golang.org/x/text"]
    version = "v0.14.0"
    hash = "sha256-yh3B0tom1RfzQBf1RNmfdNWF1PtiqxV41jW1GVS6JAg="
  [mod."google.golang.org/appengine"]
    version = "v1.6.7"
    hash = "sha256-zIxGRHiq4QBvRqkrhMGMGCaVL4iM4TtlYpAi/hrivS4="
  [mod."google.golang.org/protobuf"]
    version = "v1.31.0"
    hash = "sha256-UdIk+xRaMfdhVICvKRk1THe3R1VU+lWD8hqoW/y8jT0="
  [mod."gopkg.in/ini.v1"]
    version = "v1.67.0"
    hash = "sha256-V10ahGNGT+NLRdKUyRg1dos5RxLBXBk1xutcnquc/+4="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
