// Code generated by ObjectBox; DO NOT EDIT.
// Learn more about defining entities and generating this file - visit https://golang.objectbox.io/entity-annotations

package model

import (
	"errors"
	"github.com/google/flatbuffers/go"
	"github.com/objectbox/objectbox-go/objectbox"
	"github.com/objectbox/objectbox-go/objectbox/fbutils"
)

type video_EntityInfo struct {
	objectbox.Entity
	Uid uint64
}

var VideoBinding = video_EntityInfo{
	Entity: objectbox.Entity{
		Id: 2,
	},
	Uid: 6741263801960274516,
}

// Video_ contains type-based Property helpers to facilitate some common operations such as Queries.
var Video_ = struct {
	Id             *objectbox.PropertyUint64
	URI            *objectbox.PropertyString
	Name           *objectbox.PropertyString
	Description    *objectbox.PropertyString
	Link           *objectbox.PropertyString
	Duration       *objectbox.PropertyInt
	Width          *objectbox.PropertyInt
	Height         *objectbox.PropertyInt
	Language       *objectbox.PropertyString
	CreatedTime    *objectbox.PropertyInt64
	ModifiedTime   *objectbox.PropertyInt64
	ReleaseTime    *objectbox.PropertyInt64
	ContentRating  *objectbox.PropertyStringVector
	License        *objectbox.PropertyString
	Status         *objectbox.PropertyString
	ResourceKey    *objectbox.PropertyString
	DownloadedTime *objectbox.PropertyInt64
}{
	Id: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     1,
			Entity: &VideoBinding.Entity,
		},
	},
	URI: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     2,
			Entity: &VideoBinding.Entity,
		},
	},
	Name: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     3,
			Entity: &VideoBinding.Entity,
		},
	},
	Description: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     4,
			Entity: &VideoBinding.Entity,
		},
	},
	Link: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     5,
			Entity: &VideoBinding.Entity,
		},
	},
	Duration: &objectbox.PropertyInt{
		BaseProperty: &objectbox.BaseProperty{
			Id:     6,
			Entity: &VideoBinding.Entity,
		},
	},
	Width: &objectbox.PropertyInt{
		BaseProperty: &objectbox.BaseProperty{
			Id:     7,
			Entity: &VideoBinding.Entity,
		},
	},
	Height: &objectbox.PropertyInt{
		BaseProperty: &objectbox.BaseProperty{
			Id:     8,
			Entity: &VideoBinding.Entity,
		},
	},
	Language: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     9,
			Entity: &VideoBinding.Entity,
		},
	},
	CreatedTime: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     10,
			Entity: &VideoBinding.Entity,
		},
	},
	ModifiedTime: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     11,
			Entity: &VideoBinding.Entity,
		},
	},
	ReleaseTime: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     12,
			Entity: &VideoBinding.Entity,
		},
	},
	ContentRating: &objectbox.PropertyStringVector{
		BaseProperty: &objectbox.BaseProperty{
			Id:     13,
			Entity: &VideoBinding.Entity,
		},
	},
	License: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     14,
			Entity: &VideoBinding.Entity,
		},
	},
	Status: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     15,
			Entity: &VideoBinding.Entity,
		},
	},
	ResourceKey: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     16,
			Entity: &VideoBinding.Entity,
		},
	},
	DownloadedTime: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     17,
			Entity: &VideoBinding.Entity,
		},
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (video_EntityInfo) GeneratorVersion() int {
	return 6
}

// AddToModel is called by ObjectBox during model build
func (video_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("Video", 2, 6741263801960274516)
	model.Property("Id", 6, 1, 6323469236078112026)
	model.PropertyFlags(129)
	model.Property("URI", 9, 2, 3649540426967182990)
	model.Property("Name", 9, 3, 4552994611722894134)
	model.Property("Description", 9, 4, 7062959419176054987)
	model.Property("Link", 9, 5, 4949827082400195581)
	model.Property("Duration", 6, 6, 6844308024960516445)
	model.Property("Width", 6, 7, 1132828243380067529)
	model.Property("Height", 6, 8, 4974726543127236057)
	model.Property("Language", 9, 9, 1455235265760818980)
	model.Property("CreatedTime", 10, 10, 6632970615661739428)
	model.Property("ModifiedTime", 10, 11, 8625031358772357008)
	model.Property("ReleaseTime", 10, 12, 4002229490783755786)
	model.Property("ContentRating", 30, 13, 3212428807753209092)
	model.Property("License", 9, 14, 7947889135096176120)
	model.Property("Status", 9, 15, 3972839812277639879)
	model.Property("ResourceKey", 9, 16, 6249089389157426821)
	model.Property("DownloadedTime", 10, 17, 3157268172957756694)
	model.EntityLastPropertyId(17, 3157268172957756694)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (video_EntityInfo) GetId(object interface{}) (uint64, error) {
	return object.(*Video).Id, nil
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (video_EntityInfo) SetId(object interface{}, id uint64) error {
	object.(*Video).Id = id
	return nil
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (video_EntityInfo) PutRelated(ob *objectbox.ObjectBox, object interface{}, id uint64) error {
	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (video_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) error {
	obj := object.(*Video)
	var propCreatedTime int64
	{
		var err error
		propCreatedTime, err = objectbox.TimeInt64ConvertToDatabaseValue(obj.CreatedTime)
		if err != nil {
			return errors.New("converter objectbox.TimeInt64ConvertToDatabaseValue() failed on Video.CreatedTime: " + err.Error())
		}
	}

	var propModifiedTime int64
	{
		var err error
		propModifiedTime, err = objectbox.TimeInt64ConvertToDatabaseValue(obj.ModifiedTime)
		if err != nil {
			return errors.New("converter objectbox.TimeInt64ConvertToDatabaseValue() failed on Video.ModifiedTime: " + err.Error())
		}
	}

	var propReleaseTime int64
	{
		var err error
		propReleaseTime, err = objectbox.TimeInt64ConvertToDatabaseValue(obj.ReleaseTime)
		if err != nil {
			return errors.New("converter objectbox.TimeInt64ConvertToDatabaseValue() failed on Video.ReleaseTime: " + err.Error())
		}
	}

	var propDownloadedTime int64
	{
		var err error
		propDownloadedTime, err = objectbox.TimeInt64ConvertToDatabaseValue(obj.DownloadedTime)
		if err != nil {
			return errors.New("converter objectbox.TimeInt64ConvertToDatabaseValue() failed on Video.DownloadedTime: " + err.Error())
		}
	}

	var offsetURI = fbutils.CreateStringOffset(fbb, obj.URI)
	var offsetName = fbutils.CreateStringOffset(fbb, obj.Name)
	var offsetDescription = fbutils.CreateStringOffset(fbb, obj.Description)
	var offsetLink = fbutils.CreateStringOffset(fbb, obj.Link)
	var offsetLanguage = fbutils.CreateStringOffset(fbb, obj.Language)
	var offsetContentRating = fbutils.CreateStringVectorOffset(fbb, obj.ContentRating)
	var offsetLicense = fbutils.CreateStringOffset(fbb, obj.License)
	var offsetStatus = fbutils.CreateStringOffset(fbb, obj.Status)
	var offsetResourceKey = fbutils.CreateStringOffset(fbb, obj.ResourceKey)

	// build the FlatBuffers object
	fbb.StartObject(17)
	fbutils.SetUint64Slot(fbb, 0, id)
	fbutils.SetUOffsetTSlot(fbb, 1, offsetURI)
	fbutils.SetUOffsetTSlot(fbb, 2, offsetName)
	fbutils.SetUOffsetTSlot(fbb, 3, offsetDescription)
	fbutils.SetUOffsetTSlot(fbb, 4, offsetLink)
	fbutils.SetInt64Slot(fbb, 5, int64(obj.Duration))
	fbutils.SetInt64Slot(fbb, 6, int64(obj.Width))
	fbutils.SetInt64Slot(fbb, 7, int64(obj.Height))
	fbutils.SetUOffsetTSlot(fbb, 8, offsetLanguage)
	fbutils.SetInt64Slot(fbb, 9, propCreatedTime)
	fbutils.SetInt64Slot(fbb, 10, propModifiedTime)
	fbutils.SetInt64Slot(fbb, 11, propReleaseTime)
	fbutils.SetUOffsetTSlot(fbb, 12, offsetContentRating)
	fbutils.SetUOffsetTSlot(fbb, 13, offsetLicense)
	fbutils.SetUOffsetTSlot(fbb, 14, offsetStatus)
	fbutils.SetUOffsetTSlot(fbb, 15, offsetResourceKey)
	fbutils.SetInt64Slot(fbb, 16, propDownloadedTime)
	return nil
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (video_EntityInfo) Load(ob *objectbox.ObjectBox, bytes []byte) (interface{}, error) {
	if len(bytes) == 0 { // sanity check, should "never" happen
		return nil, errors.New("can't deserialize an object of type 'Video' - no data received")
	}

	var table = &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}

	var propId = table.GetUint64Slot(4, 0)

	propCreatedTime, err := objectbox.TimeInt64ConvertToEntityProperty(fbutils.GetInt64Slot(table, 22))
	if err != nil {
		return nil, errors.New("converter objectbox.TimeInt64ConvertToEntityProperty() failed on Video.CreatedTime: " + err.Error())
	}

	propModifiedTime, err := objectbox.TimeInt64ConvertToEntityProperty(fbutils.GetInt64Slot(table, 24))
	if err != nil {
		return nil, errors.New("converter objectbox.TimeInt64ConvertToEntityProperty() failed on Video.ModifiedTime: " + err.Error())
	}

	propReleaseTime, err := objectbox.TimeInt64ConvertToEntityProperty(fbutils.GetInt64Slot(table, 26))
	if err != nil {
		return nil, errors.New("converter objectbox.TimeInt64ConvertToEntityProperty() failed on Video.ReleaseTime: " + err.Error())
	}

	propDownloadedTime, err := objectbox.TimeInt64ConvertToEntityProperty(fbutils.GetInt64Slot(table, 36))
	if err != nil {
		return nil, errors.New("converter objectbox.TimeInt64ConvertToEntityProperty() failed on Video.DownloadedTime: " + err.Error())
	}

	return &Video{
		Id:             propId,
		URI:            fbutils.GetStringSlot(table, 6),
		Name:           fbutils.GetStringSlot(table, 8),
		Description:    fbutils.GetStringSlot(table, 10),
		Link:           fbutils.GetStringSlot(table, 12),
		Duration:       fbutils.GetIntSlot(table, 14),
		Width:          fbutils.GetIntSlot(table, 16),
		Height:         fbutils.GetIntSlot(table, 18),
		Language:       fbutils.GetStringSlot(table, 20),
		CreatedTime:    propCreatedTime,
		ModifiedTime:   propModifiedTime,
		ReleaseTime:    propReleaseTime,
		ContentRating:  fbutils.GetStringVectorSlot(table, 28),
		License:        fbutils.GetStringSlot(table, 30),
		Status:         fbutils.GetStringSlot(table, 32),
		ResourceKey:    fbutils.GetStringSlot(table, 34),
		DownloadedTime: propDownloadedTime,
	}, nil
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (video_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]*Video, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (video_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	if object == nil {
		return append(slice.([]*Video), nil)
	}
	return append(slice.([]*Video), object.(*Video))
}

// Box provides CRUD access to Video objects
type VideoBox struct {
	*objectbox.Box
}

// BoxForVideo opens a box of Video objects
func BoxForVideo(ob *objectbox.ObjectBox) *VideoBox {
	return &VideoBox{
		Box: ob.InternalBox(2),
	}
}

// Put synchronously inserts/updates a single object.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the Video.Id property on the passed object will be assigned the new ID as well.
func (box *VideoBox) Put(object *Video) (uint64, error) {
	return box.Box.Put(object)
}

// Insert synchronously inserts a single object. As opposed to Put, Insert will fail if given an ID that already exists.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the Video.Id property on the passed object will be assigned the new ID as well.
func (box *VideoBox) Insert(object *Video) (uint64, error) {
	return box.Box.Insert(object)
}

// Update synchronously updates a single object.
// As opposed to Put, Update will fail if an object with the same ID is not found in the database.
func (box *VideoBox) Update(object *Video) error {
	return box.Box.Update(object)
}

// PutAsync asynchronously inserts/updates a single object.
// Deprecated: use box.Async().Put() instead
func (box *VideoBox) PutAsync(object *Video) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutMany inserts multiple objects in single transaction.
// In case Ids are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the Video.Id property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the Video.Id assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *VideoBox) PutMany(objects []*Video) ([]uint64, error) {
	return box.Box.PutMany(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *VideoBox) Get(id uint64) (*Video, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*Video), nil
}

// GetMany reads multiple objects at once.
// If any of the objects doesn't exist, its position in the return slice is nil
func (box *VideoBox) GetMany(ids ...uint64) ([]*Video, error) {
	objects, err := box.Box.GetMany(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*Video), nil
}

// GetManyExisting reads multiple objects at once, skipping those that do not exist.
func (box *VideoBox) GetManyExisting(ids ...uint64) ([]*Video, error) {
	objects, err := box.Box.GetManyExisting(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*Video), nil
}

// GetAll reads all stored objects
func (box *VideoBox) GetAll() ([]*Video, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]*Video), nil
}

// Remove deletes a single object
func (box *VideoBox) Remove(object *Video) error {
	return box.Box.Remove(object)
}

// RemoveMany deletes multiple objects at once.
// Returns the number of deleted object or error on failure.
// Note that this method will not fail if an object is not found (e.g. already removed).
// In case you need to strictly check whether all of the objects exist before removing them,
// you can execute multiple box.Contains() and box.Remove() inside a single write transaction.
func (box *VideoBox) RemoveMany(objects ...*Video) (uint64, error) {
	var ids = make([]uint64, len(objects))
	for k, object := range objects {
		ids[k] = object.Id
	}
	return box.Box.RemoveIds(ids...)
}

// Creates a query with the given conditions. Use the fields of the Video_ struct to create conditions.
// Keep the *VideoQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *VideoBox) Query(conditions ...objectbox.Condition) *VideoQuery {
	return &VideoQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the Video_ struct to create conditions.
// Keep the *VideoQuery if you intend to execute the query multiple times.
func (box *VideoBox) QueryOrError(conditions ...objectbox.Condition) (*VideoQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &VideoQuery{query}, nil
	}
}

// Async provides access to the default Async Box for asynchronous operations. See VideoAsyncBox for more information.
func (box *VideoBox) Async() *VideoAsyncBox {
	return &VideoAsyncBox{AsyncBox: box.Box.Async()}
}

// VideoAsyncBox provides asynchronous operations on Video objects.
//
// Asynchronous operations are executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "execute & forget:" you gain faster put/remove operations as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
// In situations with (extremely) high async load, an async method may be throttled (~1ms) or delayed up to 1 second.
// In the unlikely event that the object could still not be enqueued (full queue), an error will be returned.
//
// Note that async methods do not give you hard durability guarantees like the synchronous Box provides.
// There is a small time window in which the data may not have been committed durably yet.
type VideoAsyncBox struct {
	*objectbox.AsyncBox
}

// AsyncBoxForVideo creates a new async box with the given operation timeout in case an async queue is full.
// The returned struct must be freed explicitly using the Close() method.
// It's usually preferable to use VideoBox::Async() which takes care of resource management and doesn't require closing.
func AsyncBoxForVideo(ob *objectbox.ObjectBox, timeoutMs uint64) *VideoAsyncBox {
	var async, err = objectbox.NewAsyncBox(ob, 2, timeoutMs)
	if err != nil {
		panic("Could not create async box for entity ID 2: %s" + err.Error())
	}
	return &VideoAsyncBox{AsyncBox: async}
}

// Put inserts/updates a single object asynchronously.
// When inserting a new object, the Id property on the passed object will be assigned the new ID the entity would hold
// if the insert is ultimately successful. The newly assigned ID may not become valid if the insert fails.
func (asyncBox *VideoAsyncBox) Put(object *Video) (uint64, error) {
	return asyncBox.AsyncBox.Put(object)
}

// Insert a single object asynchronously.
// The Id property on the passed object will be assigned the new ID the entity would hold if the insert is ultimately
// successful. The newly assigned ID may not become valid if the insert fails.
// Fails silently if an object with the same ID already exists (this error is not returned).
func (asyncBox *VideoAsyncBox) Insert(object *Video) (id uint64, err error) {
	return asyncBox.AsyncBox.Insert(object)
}

// Update a single object asynchronously.
// The object must already exists or the update fails silently (without an error returned).
func (asyncBox *VideoAsyncBox) Update(object *Video) error {
	return asyncBox.AsyncBox.Update(object)
}

// Remove deletes a single object asynchronously.
func (asyncBox *VideoAsyncBox) Remove(object *Video) error {
	return asyncBox.AsyncBox.Remove(object)
}

// Query provides a way to search stored objects
//
// For example, you can find all Video which Id is either 42 or 47:
//
//	box.Query(Video_.Id.In(42, 47)).Find()
type VideoQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *VideoQuery) Find() ([]*Video, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]*Video), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *VideoQuery) Offset(offset uint64) *VideoQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *VideoQuery) Limit(limit uint64) *VideoQuery {
	query.Query.Limit(limit)
	return query
}
